"""add_content_on_document_vector_table

Revision ID: 978b359dc786
Revises: d9e14bba6fc3
Create Date: 2026-01-29 15:02:38.016874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '978b359dc786'
down_revision: Union[str, None] = 'd9e14bba6fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_vectors', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_vectors', 'content')
    # ### end Alembic commands ###
