"""add_b25_index

Revision ID: a2a016ad85e1
Revises: 7326b0b268be
Create Date: 2026-02-06 16:47:05.501466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2a016ad85e1'
down_revision: Union[str, None] = '7326b0b268be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE INDEX IF NOT EXISTS docs_idx 
        ON document_vectors 
        USING bm25(content) 
        WITH (text_config='indonesian');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS docs_idx;")
    # ### end Alembic commands ###
