"""add_document_id_on_vector_table

Revision ID: d9e14bba6fc3
Revises: c5599bba6add
Create Date: 2026-01-29 12:59:20.333693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9e14bba6fc3'
down_revision: Union[str, None] = 'c5599bba6add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_vectors', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_document_vectors_document_id'), 'document_vectors', ['document_id'], unique=False)
    op.create_foreign_key(None, 'document_vectors', 'documents', ['document_id'], ['id'], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_vectors', type_='foreignkey')
    op.drop_index(op.f('ix_document_vectors_document_id'), table_name='document_vectors')
    op.drop_column('document_vectors', 'document_id')
    # ### end Alembic commands ###
