"""change_thread_title

Revision ID: f474ad455262
Revises: 978b359dc786
Create Date: 2026-01-29 16:21:20.235341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f474ad455262'
down_revision: Union[str, None] = '978b359dc786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_thread_title'), table_name='threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_threads_thread_title'), 'threads', ['thread_title'], unique=True)
    # ### end Alembic commands ###
